services:
  # API service
  # Callback Receiver
  api:
    build:
      context: .
      dockerfile: images/api/Dockerfile
    ports:
      - "80:80"
      - "81:81"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - db
      - kafka
    networks:
      - payway-network
    restart: unless-stopped
  
  # Projection Worker
  # Worker Service
  worker:
    build:
      context: .
      dockerfile: images/worker/Dockerfile
    ports:
      - "82:82"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - db
      - kafka
    networks:
      - payway-network
    restart: unless-stopped

  # PostgreSQL
  db:
    image: postgres:16.11-alpine
    environment:
      POSTGRES_DB: payway
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payway-network
    restart: unless-stopped

  # Kafka
  kafka:
    image: apache/kafka:3.8.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=abcdefghijklmnopqrstuvwx
    volumes:
      - kafka_data:/opt/kafka/data
    restart: unless-stopped
    networks:
      - payway-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8092:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - payway-network


  # # Jaeger
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "14250:14250"
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   networks:
  #     - payway-network
  #   restart: unless-stopped

  # # Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #   networks:
  #     - payway-network
  #   restart: unless-stopped

  # # Grafana для визуализации метрик
  # grafana:
  #   image: grafana/grafana-enterprise
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - payway-network
  #   restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  kafka_data:

networks:
  payway-network:
    driver: bridge